version: '3'
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        user: osman
        uid: 1000

    image: tweezer
    container_name: tweezer-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - tweezer

  nginx:
    image: nginx:1.17-alpine
    container_name: tweezer-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - tweezer

networks:
  tweezer:
    driver: bridge
